### PR TITLE
Values without decimal point or exponent should be int

### PR DESCRIPTION
**Pull request by jlyonsmith**
This fixes current issue where only 0 is an integer and all other numbers are doubles.

### CODE REVIEW

**Comment by damphat** [comment]
Nice job!

**Comment by damphat** [comment]
I don't have flutter installed in my computer right now for testing.

Do you think `int.parse` work well on flutter web?

**Comment by jlyonsmith** [comment]
The output from `dart compile js` shows that it compiles into `parseInt(source, 10)`.  That function has probably been fairly well tested by now ;)

**Comment by damphat** [comment]
https://github.com/damphat/json5-dart/releases/tag/v0.8.0
https://pub.dev/packages/json5

**Pull request merged**
